version: "3.8"

services:
  frontend:
    # build: 
    #   context: ./frontend/
    #   dockerfile: Dockerfile
    image: flamentes/mernstack-frontend
    container_name: mern-frontend
    restart: always
    ports: 
      - "3000:3000"
    networks:
      - ilker_network
    
  backend:
    # build: 
    #   context: ./backend/
    #   dockerfile: Dockerfile
    image: flamentes/mernstack-backend
    container_name: mern-backend
    restart: always
    ports: 
      - "5000:5000"
    depends_on: 
      - mongo_db
    environment:
      NODE_ENV : development
      PORT: 5000
      MONGO_URI : mongodb://mongo_db:27017
      JWT_SECRET : abc123
    networks:
      - ilker_network
    
  
  mongo_db:
    container_name: mongo_db
    image: mongo:latest
    restart: always
    volumes:
      - mongo_db:/data/db
    ports:
      - "27017:27017"
    networks:
      - ilker_network

volumes:
  mongo_db: {}

networks:
  ilker_network:

