apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: backend-deploy
  name: backend
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: backend-deploy

