apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: backend-deploy
  name: backend-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-deploy
  template:
    metadata:
      labels:
        app: backend-deploy
    spec:
      containers:
      - image: flamentes/mernstack-backend
        name: mernstack-backend
        ports:
          - containerPort: 5000
        resources: {}

