- name: nodejs node 
  hosts: _ansible_nodejs
  become: true
  tasks:
    - name: update the node
      yum:
        name: '*'
        state: latest
    - name: uninstall old versions
      yum:
        name: "{{ item }}"
        state: removed
      loop:
        - docker 
        - docker-client 
        - docker-client-latest 
        - docker-common 
        - docker-latest 
        - docker-latest-logrotate 
        - docker-logrotate 
        - docker-engine   
    - name: install yum-utils
        yum:
          name: yum-utils
          state: latest
    - name: add docker repo
      get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/dcoker-ce.repo
    - name: install docker
      package:
        name: docker-ce
        state: latest
    - name: install pip
      package:
        name: python3-pip
        state: present
    - name: install docker sdk
      pip:
        name: docker
    - name: add ec2-user to docker group
      user:
        name: ec2-user
        groups: docker
        append: yes
    - name: start docker service
      systemd:
        name: docker
        enabled: yes
        state: started
    - name: create build directory 
      file:
        path: /home/ec2-user/backend 
        state: directory 
        owner: root 
        group: root 
        mode: "0755"
    - name: copy files to the react node 
      copy: 
        src: /home/ec2-user/mern-tutorial/backend/
        dest: /home/ec2-user/backend
    - name: copy the dockerfile 
      copy:
        src: /home/ec2-user/mern-tutorial/backend/Dockerfile
        dest: /home/ec2-user/backend
    - name: remove container and image if exist 
      shell: "docker ps -q --filter 'name=flamentes_mernstack-backend' && docker stop flamentes_mernstack-backend && docker rm -fv flamentes_mernstack-backend && docker image rm -f flamentes/mernstack-backend || echo 'Not found'"
    - name: build container image 
      docker_image:
        name: flamentes/mernstack-backend
        build:
          path: /home/ec2-user/backend
        source: build 
        state: present 
    - name: create backend docker container
      docker_container:
        name: flamentes_mernstack-backend
        image: flamentes/mernstack-backend
        state: started 
        ports:
          - "5000:5000"
      register: container_info 
    - name: print container_info 
      debug: 
        var: container_info